# ==========================================================
# ðŸ§© Perfil: Desenvolvimento (localhost, debug-friendly)
# Arquivo: src/main/resources/application-dev.yml
# ==========================================================

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://163.176.145.34:5432/dev}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:Marley2015}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update  # âœ… Cria/atualiza tabelas automaticamente em DEV
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true  # Facilita leitura no log

  flyway:
    enabled: true
    baseline-on-migrate: true  # Evita erro se DB jÃ¡ tiver tabelas
    locations: classpath:db/migration

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.web: info

server:
  port: 8080  # Pode mudar pra evitar conflito com outras apps
  error:
    include-message: always
