# Perfil: desenvolvimento (localhost, debug-friendly)
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # Opcional: formatar SQL no log
        format_sql: true
    hibernate:
      ddl-auto: update  # OK em dev

server:
  #port: 8085
  # HTTP apenas em dev