spring:
  application:
    name: Per2park

spring.profiles.active: dev  # ‚Üê s√≥ define o *perfil padr√£o*; pode ser sobrescrito por `SPRING_PROFILES_ACTIVE=prod`

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

server:
  address: 0.0.0.0
  error:
    include-stacktrace: never
  forward-headers-strategy: NATIVE

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    display-request-duration: true
    doc-expansion: none
    operations-sorter: method
    tags-sorter: alpha
    syntax-highlight:
      theme: monokai
    title: "üöÄ API - Chamados"
    description: "Documenta√ß√£o da API de chamados"