spring:
  application:
    name: Per2park

  profiles:
    active: dev  # ‚Üê s√≥ define o *perfil padr√£o*; pode ser sobrescrito por `SPRING_PROFILES_ACTIVE=prod`

  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: America/Sao_Paulo

  jackson:
    time-zone: America/Sao_Paulo

  flyway:
    enabled: true
    locations: classpath:db/migration
    database: postgresql  # ‚Üê üîë Esta √© a corre√ß√£o-chave!

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

server:
  address: 0.0.0.0
  error:
    include-stacktrace: never
  forward-headers-strategy: NATIVE

#springdoc:
#  swagger-ui:
#    path: /swagger-ui/index.html
#    display-request-duration: true
#    doc-expansion: none
#    operations-sorter: method
#    tags-sorter: alpha
#    syntax-highlight:
#      theme: monokai
#    title: "üöÄ API - Chamados"
#    description: "Documenta√ß√£o da API de chamados"